before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: wdGl7bTtq4KKgsmFgoaT9fRwZUb+8GF9ASGg/Jeq6oYUs+0wuBxyy+fOUFFD+Faw8RvTEgWfI3JTdwDJtE9V0OnOfBKu1oMt9BcTEC9vL7PdVL8S3GYDqFtAOoFqL2RkU3BgS4E/7tcHSFULWqWRoY5P/MfDIp7uBuTYeG8FGkv4QdczqTfoFVnnOa7aVgm5WuF41R5oVgQ+An6YjwH2/1PXAE8zUvNRLiTDKaZxgpqBeSdjrBEXV3Zlf44C0qw9cY3j4PMloJtf6mdQOr4PhRE4LlkYuRdWPgDcMFfs5c7+Ls5MfXMU8WRrzLlVIu01vzpd1wXd01G3lRO3DOwDekvglSKH9Uf6D3PPtoVhQmTD+11VMbIDH7RxBKdQljTRJVE5AKn08VlSUwiWCzlb72Y8oBdAi46S/eErBcYQK6ISC/kxyU1/hV7AIgHNCMpPnWqr13eRjZsk0ftTVTp4GjEOxmL56WNhe8Hn15Mi3jIFxr0N0B6HIJ33QLLM0L725HxNioyQBm2STEugmpO4CDXNpxaUPG+VW7nZZKKN1tqgb9SiU+6Gnf0Xy/JzHloUr5KyjFXnk8G55uqu+99hutm3bR2dLwckRskWvd1EJQWTQaRd60+qodLZCM053gsrOw3Tzc6QsR78OUuoFCcp0x7Y0ujMl4Jk5YaBeUFIAKQ= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
